title: Athanasios K
#logo: /assets/img/headshot_circle.png
description: Computer Science graduate interested in Data Science, Data Engineer & Data Analytics
#show_downloads: true
theme: jekyll-theme-minimal
